package no.nav.integrasjon

// Exception starter
internal const val EXCEPTION = "Sorry, exception happened - "
